Portfolio: Accessibility check
Emmy-github-webdev/my-portfolio pull request #14
Opened 2021-10-05 20:08 UTC by Emmy-github-webdev

## Portfolio: Accessibility check.

In the accessibility check I:

- Test Page title: No issue found
- Test Image text alternative ** (<img alt="alt text"): Give distinct text to all the image text alternative
- Check Text headings: No issue found
- Check Color contrast: Update h2 for social media color to pass accessibility test
- Check Resize: No issue found
- Check Interaction: No issue found
- Check Moving content: No issue found
- Check Multimedia: No issue found
- The basic structure of the page: No issue found

2021-10-05 20:20 UTC, carlos-ssh requested changes
Hi @Emmy-github-webdev , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-05 20:20 UTC, carlos-ssh commented on index.html
>      <nav>
Provide a ``<title>`` with similarity to these examples:
- Emmy's portifolio
- Emmy full-stack webdeveloper

2021-10-05 20:20 UTC, carlos-ssh commented on index.html
>                    <li></li>
- Remove empty lines.

2021-10-05 20:20 UTC, carlos-ssh commented on index.html
>              </div>
**Kindly work with the design guidelines provided in your Figma template.**
- Provide margins and required paddings:
![Screen Shot 2021-10-05 at 15 17 51](https://user-images.githubusercontent.com/22258274/136096630-aef8455c-ccc8-426d-9d34-83fc0c638f05.png)

2021-10-07 16:02 UTC, SajjadAhmad14 approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

### Hi, 
## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏

## Happy Coding 👏👏👏
#### Please leave any questions or comments in the PR if you have any doubts or unclarity!
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-10 19:11 UTC, merged