Portfolio: Windows PopUp
Emmy-github-webdev/my-portfolio pull request #18
Opened 2021-10-14 19:57 UTC by Emmy-github-webdev

## Portfolio: Windows PopUp

In this project I:

- implement a popup window that includes the project details in both desktop and mobile
- use a JavaScript array to store all of the information for all projects.

2021-10-14 20:09 UTC, carlos-ssh requested changes
@Emmy-github-webdev, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._




![changesrequested](https://user-images.githubusercontent.com/22258274/137388267-1ccec0d4-b6ad-4ccf-81ac-11b4b4d58882.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 20:09 UTC, carlos-ssh commented on assets/js/script.js
> +const projects = [
- Kindly provide the requested style by the design guidelines
![Screen Shot 2021-10-14 at 15 03 22](https://user-images.githubusercontent.com/22258274/137387631-8250ba06-395c-46b8-a7d0-1dfc515b7a57.png)

2021-10-14 20:09 UTC, carlos-ssh commented on index.html
> +    <nav id="myNav" class="overlay">
- Kindly work on your design... Your mobile menu are appearing outside it:
![Screen Shot 2021-10-14 at 15 05 12](https://user-images.githubusercontent.com/22258274/137387893-f2ce6edf-4a20-46e0-af47-71243070234f.png)

2021-10-14 20:09 UTC, carlos-ssh commented on assets/js/script.js
> +
All your images are broken kindly work on it:
![Screen Shot 2021-10-14 at 15 07 18](https://user-images.githubusercontent.com/22258274/137388092-677db3cb-f478-4b4d-9f1b-2885fc5b6c92.png)

2021-10-14 20:10 UTC, carlos-ssh commented on README.md
>  # Getting Started
- PROVIDE A LICENSE.

2021-10-15 13:54 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Emmanuel, 
 ### Thank you for working on changes suggested previously :ok_hand:

## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-15 13:54 UTC, SajjadAhmad14 commented on assets/js/script.js
> +    createProjectBtn.textContent = 'See Project';
Pop-up on the desktop is still missing key design elements. Please use the same font as mentioned in the design. The buttons on the right side are overlapping. Moreover please make the main content on background blur as can be seen in the design.
![pop-desktop](https://user-images.githubusercontent.com/35504149/137498352-81dde2c9-1a18-4aee-98f1-4360324acb9d.png)

2021-10-15 13:54 UTC, SajjadAhmad14 commented on assets/js/script.js
> +    createProjectBtn.textContent = 'See Project';
Buttons are overflowing out of the pop-up on mobile view. Please follow the font guidelines from the design.
![pop-mobile](https://user-images.githubusercontent.com/35504149/137498635-6b44beb0-8497-4aa6-a29a-b48601cacd69.png)

2021-10-15 18:32 UTC, GzimAsani approved these changes
# STATUS: APPROVED :100:         
## Thank you for implementing all the project requirements, you've done a great job :trophy:  . There is nothing else to say other than... it's time to merge it :champagne:  :tada: Congratulations

Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please adjust the picture to match the original it should be on the same line as the text. Check picture:
![Screenshot from 2021-10-15 20-24-52](https://user-images.githubusercontent.com/62705947/137535710-e7304d77-f3ac-4a38-870d-ca86bd35b43a.png)

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-10-15 18:38 UTC, merged